### ISSUE TITLE
NativeAOT-LLVM: Constrained GVM test failure in Generics.cs

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1484]
With the latest changes to `Generics.cs` test , the LLVM backend is hitting an assert for the method ``{[Generics]Program+TestConstrainedGvmValueTypeCalls.DoFrob2<Bar`1<__Canon>,__Canon>(Bar`1<__Canon>&,object)}`` and the call here https://github.com/dotnet/runtimelab/blob/1a17135e426efb389cce6042ddfb5d05c64f5291/src/tests/nativeaot/SmokeTests/Generics/Generics.cs#L2764-L2768.

It hits the assert at https://github.com/dotnet/runtimelab/blob/23feaa85546690e611531ee0d6113077f8d64708/src/coreclr/tools/aot/ILCompiler.LLVM/CodeGen/ILToLLVMImporter.cs#L2659 .   It pickups the `constrainedType` ok ``{T_.Bar`1<System.__Canon>}``, so the `canonMethod.RequiresInstMethodTableArg()` is false.  `canonMethod` is ``{[Generics]Program+TestConstrainedGvmValueTypeCalls+Bar`1<System.__Canon>.Frob<__Canon>(object)}``.

I just wondered if fixing up the `Generics.cs` tests for LLVM would be expected to be easy? No problem if not, I'll just `#if` them out for IL->LLVM and leave them for RyuJIT->LLVM at a later date.

**Comment by yowl** [comment]
@MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Maybe it's not too difficult to fix it up.

`RequiresInstMethodTableArg()` will be false for generic methods always - they `RequireInstMethodDescArg()` instead (the generic context is the method generic dictionary, not `this`).

* Loosen the assert to `canonMethod.RequiresInstArg()`
* In the `constrainedType.IsRuntimeDeterminedSubtype` branch, make this look up `ReadyToRunHelperId.TypeHandle` if `RequiresInstMethodTableArg`, but `ReadyToRunHelperId.MethodDictionary` otherwise.
* In the else branch constrainedTypeSymbol is ConstructedTypeSymbol if RequiresInstMethodTableArg, but MethodGenericDictionary otherwise.

**Comment by MichalStrehovsky** [comment]
You might also need to do this dance to get the actual method for the IsRuntimeDeterminedSubtype path:

https://github.com/dotnet/runtimelab/blob/1a17135e426efb389cce6042ddfb5d05c64f5291/src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs#L527-L537

(As you wrote above, `canonMethod` is ```{[Generics]Program+TestConstrainedGvmValueTypeCalls+Bar`1<System.__Canon>.Frob<__Canon>(object)}``` but we need it in the runtime determined form so that we can substitute generic arguments - plain __Canon cannot be substituted anymore)

**Comment by yowl** [comment]
Thanks, Yes that compiles now.  I do have a runtime exception with `MakeGenericMethod` on a derived type, 
```
vm1 = typeof(DerivedClass1<string>).GetTypeInfo().GetDeclaredMethod("GVMethod1").MakeGenericMethod(typeof(string))
```
But I think that is unrelated to this path as I dont see a breakpoint in this logic getting hit at compile time.

**Comment by yowl** [comment]
Just to follow up my last message,   It does look like something else, a dependency not getting added.  The current NativeAOT-LLVM head can run the generics test, but if all the tests are removed except this one, then it fails.

**Comment by MichalStrehovsky** [comment]
I believe this is all resolved now.

**Comment by yowl** [comment]
I still have a failure with these tests pulling in later code.

```
exception thrown: RuntimeError: abort(undefined) at Error
    at jsStackTrace (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1656:19)
    at stackTrace (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1673:16)
    at abort (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:1389:44)
    at _abort (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:5814:7)
    at Assert(char const*, char const*, unsigned int, char const*) (wasm-function[20538]:0xe3b815)
    at RhpNewFinalizableAlign8 (wasm-function[20788]:0xe48d8f)
    at S_P_CoreLib_System_Runtime_RuntimeExports__RhNewObject (wasm-function[115]:0xd786)
    at S_P_CoreLib_System_Buffers_ArrayPoolEventSource___cctor (wasm-function[4475]:0x284eea)
    at invoke_vi (E:\GitHub\runtimelab2\artifacts\tests\coreclr\Browser.wasm.Debug\nativeaot\SmokeTests\Generics\Generics\native\Generics.js:7359:25)
    at S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun (wasm-function[283]:0x23de1)
    at S_P_CoreLib_System_Buffers_TlsOverPerCoreLockedStacksArrayPool_1<Char>__Rent (wasm-function[3460]:0x21d9a3)
    at S_P_CoreLib_System_Runtime_CompilerServices_DefaultInterpolatedStringHandler___ctor (wasm-function[1418]:0xe4ffa)
    at Generics_Program_TestGvmDependenciesFromLazy_Bar__Frob<System___Canon> (wasm-function[3717]:0x23a01c)
    at Generics_Program_TestGvmDependenciesFromLazy_Foo__FrobToo<System___Canon> (wasm-function[3039]:0x1ca68d)
    at Generics_Program_TestGvmDependenciesFromLazy__Run (wasm-function[977]:0xa011e)
    at Generics_Program__Main (wasm-function[952]:0x817a0)
    at Generics__Module___MainMethodWrapper (wasm-function[20425]:0xe3ab0b)
    at StartupCodeMain (wasm-function[426]:0x32aa5)
```

Memory corruption due to outstanding virtual alloc/dealloc issues or related to `TestGvmDependenciesFromLazy` changes that went in in July.  Need to investigate some more.
