### ISSUE TITLE
Unable to allocate very big arrays

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#939]
We have System.Runtime tests that test allocating the maximally supported arrays. We throw an OutOfMemoryException for them. Likely because this code:

https://github.com/dotnet/runtimelab/blob/8fac0a891011eda3633270199934019faeea002c/src/coreclr/nativeaot/Runtime/gcrhenv.cpp#L239-L263

Is checking the allocation size instead of element count. Allocation size has already been aligned up.

**Comment by jkotas** [comment]
Fixed in #971

**Comment by MichalStrehovsky** [comment]
The test is still failing. I think the problem is still that we are comparing the element count to the limit only after we don't have the actual element count anymore and we need to recompute it from the allocation size. The allocation size has already been aligned up to what the GC needs so it looks like we want more elements than what was requested.

**Comment by jkotas** [comment]
The test is passing for me now.
